service: amped

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  region: ${env:AWS_DEFAULT_REGION, "ap-southeast-2"}
  stage: ${env:STAGE, "dev"}

plugins:
  - serverless-finch
  - serverless-webpack
  - serverless-offline

custom:
  client:
    bucketName: ${env:AMPED_APP_BUCKET}
    distributionFolder: ../app/.build
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: yarn

functions:
  data:
    handler: src/handler.handler
    events:
      - http:
          path: /
          method: GET
          cors: true
      - http:
          path: /{any+}
          method: GET
          cors: true
    environment:
      AMPED_DATA_BUCKET: ${env:AMPED_DATA_BUCKET}
      SLS_REGION: ${self:provider.region}

resources:
  Description: Amped!
